version: '3.6'

services:
  pubsub_app:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    image: pubsub/pubsub:1.0
    restart: always
    environment:
      NODE_NAME: pubsub
      NODE_HOST: "localhost"

